### ISSUE TITLE
"has_cap was called with an argument that is deprecated since version 2.0!"

### ISSUE THREAD

**Issue by travisseitler** [hiddentao/wp-flickr-embed#16]
_PHP Notice: has_cap was called with an argument that is **deprecated** since version 2.0! Usage of user levels by plugins and themes is deprecated. Use roles and capabilities instead._

The notice above is caused by **line 223** in _wp-flickr-embed.php_:

`add_options_page(__('WP Flickr Embed', 'wp-flickr-embed'), __('WP Flickr Embed', 'wp-flickr-embed'), 8, $this->pagesDir.'/admin.php');`

The `8` in there should be replaced with an equivalent WP _capability_, i.e. `edit_plugins` or `manage_options` (see http://codex.wordpress.org/Roles_and_Capabilities).

**Comment by tychay** [comment]
Yes, I got the same thing. This notice will show when wp_debug is true

**Comment by hiddentao** [comment]
Thanks for PR.
